---
- name: "Get {{ user }}'s home directory"
  command: "grep {{ user }} /etc/passwd"
  register: grep_result

- name: "Create user_home variable"
  set_fact:
    user_home: "{{ grep_result.stdout.split(':')[-2] }}"

- name: "Clone oh-my-zsh"
  git:
    repo: "{{ oh_my_zsh_repo }}"
    dest: "{{ user_home }}/.oh-my-zsh"
    depth: 1
  become_user: "{{ user }}"